### ISSUE TITLE
Understanding the flow of iob-cache

### ISSUE THREAD

**Issue by krritd23** [IObundle/iob-cache#175]
Hello Community
Is there any user documentation which explains basic flow of the "iob-cache" and how can we understand it.? I am getting perplexed  with files getting generated after verilation in obj_dir directory. I am unable to  generate user guide with the minimal commands provided.
It is getting difficult in understand as a user, how the back-end ,front-end sections are in sync with main memory section and can they be tested from testbench
Which sequence to follow for a basic successful test case

Thank you in advance.

**Comment by jjts** [comment]
We are adding a basic test to the verilator testbench. It should be ready in a couple of days.

This test writes to one memory address and then reads from the same address.

An external memory is missing from the verilator  testbench. Of course a cache does not work without a memory attached. 

As for the user guide it was working when I last tried though the document needs reviewing and is incomplete. Is it because of the FPGA compilation? You need to have vivado and quarts installed but it makes sense to disable that and not include implementation results by default.

**Comment by krritd23** [comment]
I have simulated testbench by adding the below changes. I wanted to see the output to analyse the changes But i dont even see the "clk" changes in gtkwave 
![20220523_173604](https://user-images.githubusercontent.com/105431075/169815694-7eab8920-71cf-49b7-8bc3-b0c3c0a100e4.jpg)
![20220523_173713](https://user-images.githubusercontent.com/105431075/169815726-ca198223-9c10-475f-8b06-698da0c56b0d.jpg)
Could you pleaee suggest in which manner i can configure such changes in testbench.cpp ..
Thank you in advance

**Comment by codingUniv** [comment]
Hello
Please refer to the updated verilator testbench available on doc branch. It performs a simple write/read test.
I hope it could help.

**Comment by jjts** [comment]
Documentation can now be generated on branch build-lib. Thanks.
